// Code generated by protoc-gen-go. DO NOT EDIT.
// source: karyawan.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	karyawan.proto

It has these top-level messages:
	AddKaryawanReq
	ReadKaryawanByTeleponReq
	ReadKaryawanByTeleponResp
	ReadKaryawanResp
	UpdateKaryawanReq
	ReadKaryawanByNamaReq
	ReadKaryawanByNamaResp
	ReadKaryawanByKeteranganReq
	ReadKaryawanByKeteranganResp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddKaryawanReq struct {
	IdKaryawan   string `protobuf:"bytes,1,opt,name=idKaryawan" json:"idKaryawan,omitempty"`
	NamaKaryawan string `protobuf:"bytes,2,opt,name=namaKaryawan" json:"namaKaryawan,omitempty"`
	Alamat       string `protobuf:"bytes,3,opt,name=alamat" json:"alamat,omitempty"`
	NoTelepon    string `protobuf:"bytes,4,opt,name=noTelepon" json:"noTelepon,omitempty"`
	Keterangan   string `protobuf:"bytes,5,opt,name=keterangan" json:"keterangan,omitempty"`
	IdJabatan    string `protobuf:"bytes,6,opt,name=idJabatan" json:"idJabatan,omitempty"`
	IdDepartemen string `protobuf:"bytes,7,opt,name=idDepartemen" json:"idDepartemen,omitempty"`
	IdGolongan   string `protobuf:"bytes,8,opt,name=idGolongan" json:"idGolongan,omitempty"`
	IdKontrak    string `protobuf:"bytes,9,opt,name=idKontrak" json:"idKontrak,omitempty"`
	Status       string `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
}

func (m *AddKaryawanReq) Reset()                    { *m = AddKaryawanReq{} }
func (m *AddKaryawanReq) String() string            { return proto.CompactTextString(m) }
func (*AddKaryawanReq) ProtoMessage()               {}
func (*AddKaryawanReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddKaryawanReq) GetIdKaryawan() string {
	if m != nil {
		return m.IdKaryawan
	}
	return ""
}

func (m *AddKaryawanReq) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

func (m *AddKaryawanReq) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *AddKaryawanReq) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *AddKaryawanReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *AddKaryawanReq) GetIdJabatan() string {
	if m != nil {
		return m.IdJabatan
	}
	return ""
}

func (m *AddKaryawanReq) GetIdDepartemen() string {
	if m != nil {
		return m.IdDepartemen
	}
	return ""
}

func (m *AddKaryawanReq) GetIdGolongan() string {
	if m != nil {
		return m.IdGolongan
	}
	return ""
}

func (m *AddKaryawanReq) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *AddKaryawanReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadKaryawanByTeleponReq struct {
	NoTelepon string `protobuf:"bytes,1,opt,name=noTelepon" json:"noTelepon,omitempty"`
}

func (m *ReadKaryawanByTeleponReq) Reset()                    { *m = ReadKaryawanByTeleponReq{} }
func (m *ReadKaryawanByTeleponReq) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByTeleponReq) ProtoMessage()               {}
func (*ReadKaryawanByTeleponReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadKaryawanByTeleponReq) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

type ReadKaryawanByTeleponResp struct {
	IdKaryawan   string `protobuf:"bytes,1,opt,name=idKaryawan" json:"idKaryawan,omitempty"`
	NamaKaryawan string `protobuf:"bytes,2,opt,name=namaKaryawan" json:"namaKaryawan,omitempty"`
	Alamat       string `protobuf:"bytes,3,opt,name=alamat" json:"alamat,omitempty"`
	NoTelepon    string `protobuf:"bytes,4,opt,name=noTelepon" json:"noTelepon,omitempty"`
	Keterangan   string `protobuf:"bytes,5,opt,name=keterangan" json:"keterangan,omitempty"`
	IdJabatan    string `protobuf:"bytes,6,opt,name=idJabatan" json:"idJabatan,omitempty"`
	IdDepartemen string `protobuf:"bytes,7,opt,name=idDepartemen" json:"idDepartemen,omitempty"`
	IdGolongan   string `protobuf:"bytes,8,opt,name=idGolongan" json:"idGolongan,omitempty"`
	IdKontrak    string `protobuf:"bytes,9,opt,name=idKontrak" json:"idKontrak,omitempty"`
	Status       string `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
}

func (m *ReadKaryawanByTeleponResp) Reset()                    { *m = ReadKaryawanByTeleponResp{} }
func (m *ReadKaryawanByTeleponResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByTeleponResp) ProtoMessage()               {}
func (*ReadKaryawanByTeleponResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadKaryawanByTeleponResp) GetIdKaryawan() string {
	if m != nil {
		return m.IdKaryawan
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetIdJabatan() string {
	if m != nil {
		return m.IdJabatan
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetIdDepartemen() string {
	if m != nil {
		return m.IdDepartemen
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetIdGolongan() string {
	if m != nil {
		return m.IdGolongan
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *ReadKaryawanByTeleponResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadKaryawanResp struct {
	AllKaryawan []*ReadKaryawanByTeleponResp `protobuf:"bytes,1,rep,name=allKaryawan" json:"allKaryawan,omitempty"`
}

func (m *ReadKaryawanResp) Reset()                    { *m = ReadKaryawanResp{} }
func (m *ReadKaryawanResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanResp) ProtoMessage()               {}
func (*ReadKaryawanResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadKaryawanResp) GetAllKaryawan() []*ReadKaryawanByTeleponResp {
	if m != nil {
		return m.AllKaryawan
	}
	return nil
}

type UpdateKaryawanReq struct {
	IdKaryawan   string `protobuf:"bytes,1,opt,name=idKaryawan" json:"idKaryawan,omitempty"`
	NamaKaryawan string `protobuf:"bytes,2,opt,name=namaKaryawan" json:"namaKaryawan,omitempty"`
	Alamat       string `protobuf:"bytes,3,opt,name=alamat" json:"alamat,omitempty"`
	NoTelepon    string `protobuf:"bytes,4,opt,name=noTelepon" json:"noTelepon,omitempty"`
	Keterangan   string `protobuf:"bytes,5,opt,name=keterangan" json:"keterangan,omitempty"`
	IdJabatan    string `protobuf:"bytes,6,opt,name=idJabatan" json:"idJabatan,omitempty"`
	IdDepartemen string `protobuf:"bytes,7,opt,name=idDepartemen" json:"idDepartemen,omitempty"`
	IdGolongan   string `protobuf:"bytes,8,opt,name=idGolongan" json:"idGolongan,omitempty"`
	IdKontrak    string `protobuf:"bytes,9,opt,name=idKontrak" json:"idKontrak,omitempty"`
	Status       string `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateKaryawanReq) Reset()                    { *m = UpdateKaryawanReq{} }
func (m *UpdateKaryawanReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateKaryawanReq) ProtoMessage()               {}
func (*UpdateKaryawanReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateKaryawanReq) GetIdKaryawan() string {
	if m != nil {
		return m.IdKaryawan
	}
	return ""
}

func (m *UpdateKaryawanReq) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

func (m *UpdateKaryawanReq) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *UpdateKaryawanReq) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *UpdateKaryawanReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *UpdateKaryawanReq) GetIdJabatan() string {
	if m != nil {
		return m.IdJabatan
	}
	return ""
}

func (m *UpdateKaryawanReq) GetIdDepartemen() string {
	if m != nil {
		return m.IdDepartemen
	}
	return ""
}

func (m *UpdateKaryawanReq) GetIdGolongan() string {
	if m != nil {
		return m.IdGolongan
	}
	return ""
}

func (m *UpdateKaryawanReq) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *UpdateKaryawanReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadKaryawanByNamaReq struct {
	NamaKaryawan string `protobuf:"bytes,1,opt,name=namaKaryawan" json:"namaKaryawan,omitempty"`
}

func (m *ReadKaryawanByNamaReq) Reset()                    { *m = ReadKaryawanByNamaReq{} }
func (m *ReadKaryawanByNamaReq) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByNamaReq) ProtoMessage()               {}
func (*ReadKaryawanByNamaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadKaryawanByNamaReq) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

type ReadKaryawanByNamaResp struct {
	IdKaryawan   string `protobuf:"bytes,1,opt,name=idKaryawan" json:"idKaryawan,omitempty"`
	NamaKaryawan string `protobuf:"bytes,2,opt,name=namaKaryawan" json:"namaKaryawan,omitempty"`
	Alamat       string `protobuf:"bytes,3,opt,name=alamat" json:"alamat,omitempty"`
	NoTelepon    string `protobuf:"bytes,4,opt,name=noTelepon" json:"noTelepon,omitempty"`
	Keterangan   string `protobuf:"bytes,5,opt,name=keterangan" json:"keterangan,omitempty"`
	IdJabatan    string `protobuf:"bytes,6,opt,name=idJabatan" json:"idJabatan,omitempty"`
	IdDepartemen string `protobuf:"bytes,7,opt,name=idDepartemen" json:"idDepartemen,omitempty"`
	IdGolongan   string `protobuf:"bytes,8,opt,name=idGolongan" json:"idGolongan,omitempty"`
	IdKontrak    string `protobuf:"bytes,9,opt,name=idKontrak" json:"idKontrak,omitempty"`
	Status       string `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
}

func (m *ReadKaryawanByNamaResp) Reset()                    { *m = ReadKaryawanByNamaResp{} }
func (m *ReadKaryawanByNamaResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByNamaResp) ProtoMessage()               {}
func (*ReadKaryawanByNamaResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadKaryawanByNamaResp) GetIdKaryawan() string {
	if m != nil {
		return m.IdKaryawan
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetIdJabatan() string {
	if m != nil {
		return m.IdJabatan
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetIdDepartemen() string {
	if m != nil {
		return m.IdDepartemen
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetIdGolongan() string {
	if m != nil {
		return m.IdGolongan
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadKaryawanByKeteranganReq struct {
	Keterangan string `protobuf:"bytes,1,opt,name=Keterangan" json:"Keterangan,omitempty"`
}

func (m *ReadKaryawanByKeteranganReq) Reset()                    { *m = ReadKaryawanByKeteranganReq{} }
func (m *ReadKaryawanByKeteranganReq) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByKeteranganReq) ProtoMessage()               {}
func (*ReadKaryawanByKeteranganReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadKaryawanByKeteranganReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadKaryawanByKeteranganResp struct {
	AllKeterangan []*ReadKaryawanByNamaResp `protobuf:"bytes,1,rep,name=allKeterangan" json:"allKeterangan,omitempty"`
}

func (m *ReadKaryawanByKeteranganResp) Reset()                    { *m = ReadKaryawanByKeteranganResp{} }
func (m *ReadKaryawanByKeteranganResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByKeteranganResp) ProtoMessage()               {}
func (*ReadKaryawanByKeteranganResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReadKaryawanByKeteranganResp) GetAllKeterangan() []*ReadKaryawanByNamaResp {
	if m != nil {
		return m.AllKeterangan
	}
	return nil
}

func init() {
	proto.RegisterType((*AddKaryawanReq)(nil), "grpc.AddKaryawanReq")
	proto.RegisterType((*ReadKaryawanByTeleponReq)(nil), "grpc.ReadKaryawanByTeleponReq")
	proto.RegisterType((*ReadKaryawanByTeleponResp)(nil), "grpc.ReadKaryawanByTeleponResp")
	proto.RegisterType((*ReadKaryawanResp)(nil), "grpc.ReadKaryawanResp")
	proto.RegisterType((*UpdateKaryawanReq)(nil), "grpc.UpdateKaryawanReq")
	proto.RegisterType((*ReadKaryawanByNamaReq)(nil), "grpc.ReadKaryawanByNamaReq")
	proto.RegisterType((*ReadKaryawanByNamaResp)(nil), "grpc.ReadKaryawanByNamaResp")
	proto.RegisterType((*ReadKaryawanByKeteranganReq)(nil), "grpc.ReadKaryawanByKeteranganReq")
	proto.RegisterType((*ReadKaryawanByKeteranganResp)(nil), "grpc.ReadKaryawanByKeteranganResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for KaryawanService service

type KaryawanServiceClient interface {
	AddKaryawan(ctx context.Context, in *AddKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadKaryawanByTelepon(ctx context.Context, in *ReadKaryawanByTeleponReq, opts ...grpc1.CallOption) (*ReadKaryawanByTeleponResp, error)
	ReadKaryawan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKaryawanResp, error)
	UpdateKaryawan(ctx context.Context, in *UpdateKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadKaryawanByNama(ctx context.Context, in *ReadKaryawanByNamaReq, opts ...grpc1.CallOption) (*ReadKaryawanByNamaResp, error)
	ReadKaryawanByKeterangan(ctx context.Context, in *ReadKaryawanByKeteranganReq, opts ...grpc1.CallOption) (*ReadKaryawanByKeteranganResp, error)
}

type karyawanServiceClient struct {
	cc *grpc1.ClientConn
}

func NewKaryawanServiceClient(cc *grpc1.ClientConn) KaryawanServiceClient {
	return &karyawanServiceClient{cc}
}

func (c *karyawanServiceClient) AddKaryawan(ctx context.Context, in *AddKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/AddKaryawan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) ReadKaryawanByTelepon(ctx context.Context, in *ReadKaryawanByTeleponReq, opts ...grpc1.CallOption) (*ReadKaryawanByTeleponResp, error) {
	out := new(ReadKaryawanByTeleponResp)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/ReadKaryawanByTelepon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) ReadKaryawan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKaryawanResp, error) {
	out := new(ReadKaryawanResp)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/ReadKaryawan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) UpdateKaryawan(ctx context.Context, in *UpdateKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/UpdateKaryawan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) ReadKaryawanByNama(ctx context.Context, in *ReadKaryawanByNamaReq, opts ...grpc1.CallOption) (*ReadKaryawanByNamaResp, error) {
	out := new(ReadKaryawanByNamaResp)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/ReadKaryawanByNama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) ReadKaryawanByKeterangan(ctx context.Context, in *ReadKaryawanByKeteranganReq, opts ...grpc1.CallOption) (*ReadKaryawanByKeteranganResp, error) {
	out := new(ReadKaryawanByKeteranganResp)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/ReadKaryawanByKeterangan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KaryawanService service

type KaryawanServiceServer interface {
	AddKaryawan(context.Context, *AddKaryawanReq) (*google_protobuf.Empty, error)
	ReadKaryawanByTelepon(context.Context, *ReadKaryawanByTeleponReq) (*ReadKaryawanByTeleponResp, error)
	ReadKaryawan(context.Context, *google_protobuf.Empty) (*ReadKaryawanResp, error)
	UpdateKaryawan(context.Context, *UpdateKaryawanReq) (*google_protobuf.Empty, error)
	ReadKaryawanByNama(context.Context, *ReadKaryawanByNamaReq) (*ReadKaryawanByNamaResp, error)
	ReadKaryawanByKeterangan(context.Context, *ReadKaryawanByKeteranganReq) (*ReadKaryawanByKeteranganResp, error)
}

func RegisterKaryawanServiceServer(s *grpc1.Server, srv KaryawanServiceServer) {
	s.RegisterService(&_KaryawanService_serviceDesc, srv)
}

func _KaryawanService_AddKaryawan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKaryawanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).AddKaryawan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/AddKaryawan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).AddKaryawan(ctx, req.(*AddKaryawanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_ReadKaryawanByTelepon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKaryawanByTeleponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).ReadKaryawanByTelepon(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/ReadKaryawanByTelepon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).ReadKaryawanByTelepon(ctx, req.(*ReadKaryawanByTeleponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_ReadKaryawan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).ReadKaryawan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/ReadKaryawan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).ReadKaryawan(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_UpdateKaryawan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKaryawanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).UpdateKaryawan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/UpdateKaryawan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).UpdateKaryawan(ctx, req.(*UpdateKaryawanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_ReadKaryawanByNama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKaryawanByNamaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).ReadKaryawanByNama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/ReadKaryawanByNama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).ReadKaryawanByNama(ctx, req.(*ReadKaryawanByNamaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_ReadKaryawanByKeterangan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKaryawanByKeteranganReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).ReadKaryawanByKeterangan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/ReadKaryawanByKeterangan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).ReadKaryawanByKeterangan(ctx, req.(*ReadKaryawanByKeteranganReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _KaryawanService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.KaryawanService",
	HandlerType: (*KaryawanServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddKaryawan",
			Handler:    _KaryawanService_AddKaryawan_Handler,
		},
		{
			MethodName: "ReadKaryawanByTelepon",
			Handler:    _KaryawanService_ReadKaryawanByTelepon_Handler,
		},
		{
			MethodName: "ReadKaryawan",
			Handler:    _KaryawanService_ReadKaryawan_Handler,
		},
		{
			MethodName: "UpdateKaryawan",
			Handler:    _KaryawanService_UpdateKaryawan_Handler,
		},
		{
			MethodName: "ReadKaryawanByNama",
			Handler:    _KaryawanService_ReadKaryawanByNama_Handler,
		},
		{
			MethodName: "ReadKaryawanByKeterangan",
			Handler:    _KaryawanService_ReadKaryawanByKeterangan_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "karyawan.proto",
}

func init() { proto.RegisterFile("karyawan.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x4d, 0x9c, 0x12, 0xc8, 0xa4, 0x04, 0x58, 0x41, 0x58, 0x9c, 0x88, 0x8f, 0x3d, 0xf5, 0xe4,
	0x4a, 0xe5, 0x82, 0x84, 0x2a, 0xd1, 0x02, 0x42, 0x22, 0x12, 0x12, 0x86, 0x5e, 0xb8, 0x4d, 0xe2,
	0x25, 0x8a, 0x62, 0xef, 0x3a, 0xf6, 0x16, 0x94, 0xbf, 0x87, 0xc4, 0x05, 0x89, 0x5f, 0xc2, 0x9f,
	0x40, 0xeb, 0xf5, 0x77, 0xe2, 0x54, 0xd0, 0x6b, 0x8e, 0x7e, 0x9e, 0xb7, 0x33, 0xef, 0xcd, 0xce,
	0x0e, 0x0c, 0x96, 0x18, 0xad, 0xf1, 0x3b, 0x0a, 0x27, 0x8c, 0xa4, 0x92, 0xe4, 0x60, 0x1e, 0x85,
	0x33, 0x7b, 0x34, 0x97, 0x72, 0xee, 0xf3, 0xe3, 0x04, 0x9b, 0x5e, 0x7e, 0x3d, 0xe6, 0x41, 0xa8,
	0xd6, 0x26, 0x84, 0xfd, 0xb0, 0x60, 0x70, 0xe6, 0x79, 0x93, 0x94, 0xe8, 0xf2, 0x15, 0x79, 0x0c,
	0xb0, 0xc8, 0x01, 0xda, 0x7e, 0xda, 0x3e, 0xea, 0xb9, 0x25, 0x84, 0x30, 0x38, 0x14, 0x18, 0x60,
	0x1e, 0x61, 0x25, 0x11, 0x15, 0x8c, 0x0c, 0xa1, 0x8b, 0x3e, 0x06, 0xa8, 0x68, 0x27, 0xf9, 0x9b,
	0x7e, 0x91, 0x31, 0xf4, 0x84, 0xfc, 0xcc, 0x7d, 0x1e, 0x4a, 0x41, 0x0f, 0x92, 0x5f, 0x05, 0xa0,
	0x33, 0x2f, 0xb9, 0xe2, 0x11, 0x8a, 0x39, 0x0a, 0x7a, 0xc3, 0x64, 0x2e, 0x10, 0xcd, 0x5e, 0x78,
	0xef, 0x71, 0x8a, 0x0a, 0x05, 0xed, 0x1a, 0x76, 0x0e, 0xe8, 0xba, 0x16, 0xde, 0x1b, 0x1e, 0x62,
	0xa4, 0x78, 0xc0, 0x05, 0xbd, 0x69, 0xea, 0x2a, 0x63, 0x46, 0xdb, 0x3b, 0xe9, 0xcb, 0x24, 0xc3,
	0xad, 0x4c, 0x5b, 0x86, 0x98, 0x0c, 0x13, 0x29, 0x54, 0x84, 0x4b, 0xda, 0xcb, 0x32, 0xa4, 0x80,
	0x56, 0x15, 0x2b, 0x54, 0x97, 0x31, 0x05, 0xa3, 0xca, 0x7c, 0xb1, 0x17, 0x40, 0x5d, 0x8e, 0xb9,
	0x43, 0xe7, 0xeb, 0x54, 0x90, 0x76, 0xb3, 0xa2, 0xb8, 0x5d, 0x53, 0xcc, 0x7e, 0x5b, 0xf0, 0xa8,
	0x81, 0x1a, 0x87, 0xfb, 0x4e, 0xfc, 0x73, 0x27, 0x2e, 0xe0, 0x6e, 0xd9, 0xce, 0xc4, 0xc5, 0x33,
	0xe8, 0xa3, 0xef, 0x97, 0x6c, 0xec, 0x1c, 0xf5, 0x4f, 0x9e, 0x38, 0x7a, 0x36, 0x9c, 0x46, 0xef,
	0xdd, 0x32, 0x87, 0xfd, 0xb4, 0xe0, 0xde, 0x45, 0xe8, 0xa1, 0xe2, 0xfb, 0x41, 0xb9, 0x4e, 0x7b,
	0x5e, 0xc2, 0x83, 0xaa, 0xe3, 0x1f, 0x30, 0x40, 0x6d, 0x65, 0xdd, 0xaa, 0xf6, 0xa6, 0x55, 0xec,
	0x97, 0x05, 0xc3, 0x6d, 0xec, 0xfd, 0xa0, 0xfc, 0x47, 0x27, 0x4e, 0x61, 0x54, 0xf5, 0x72, 0x92,
	0xd7, 0x9c, 0x5e, 0xed, 0x02, 0xc8, 0x0c, 0x2d, 0x10, 0x36, 0x85, 0x71, 0x33, 0x3d, 0x0e, 0xc9,
	0x39, 0xdc, 0xd6, 0xf3, 0x53, 0x3e, 0x42, 0x4f, 0xdd, 0x78, 0xdb, 0xd4, 0x65, 0x5d, 0x74, 0xab,
	0x94, 0x93, 0x3f, 0x1d, 0xb8, 0x93, 0x45, 0x7d, 0xe2, 0xd1, 0xb7, 0xc5, 0x8c, 0x93, 0x53, 0xe8,
	0x97, 0xb6, 0x15, 0xb9, 0x6f, 0xce, 0xab, 0x2e, 0x30, 0x7b, 0xe8, 0x98, 0x8d, 0xe7, 0x64, 0x1b,
	0xcf, 0x79, 0xab, 0x37, 0x1e, 0x6b, 0x91, 0x2f, 0xf5, 0xfb, 0x97, 0xb7, 0x71, 0xe7, 0x73, 0xb0,
	0xb2, 0xaf, 0x7a, 0x2e, 0x58, 0x8b, 0xbc, 0x82, 0xc3, 0xf2, 0x6f, 0xd2, 0x50, 0x85, 0xae, 0xae,
	0x7e, 0x54, 0x7a, 0xc2, 0x6b, 0x18, 0x54, 0x1f, 0x19, 0xf2, 0xd0, 0xc4, 0x6e, 0x3c, 0x3d, 0x3b,
	0x24, 0x7e, 0x04, 0xb2, 0x69, 0x2f, 0x19, 0x35, 0x1b, 0xbf, 0xb2, 0x77, 0x76, 0x85, 0xb5, 0xc8,
	0xac, 0xbe, 0xde, 0x8a, 0x26, 0x91, 0x67, 0xdb, 0xb8, 0x95, 0xbb, 0x64, 0xb3, 0xab, 0x42, 0x74,
	0x92, 0x69, 0x37, 0x51, 0xf2, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0xb9, 0xb4, 0x97,
	0xc4, 0x08, 0x00, 0x00,
}
