// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kontrak.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	kontrak.proto

It has these top-level messages:
	AddKontrakReq
	ReadKontrakBySelesaiReq
	ReadKontrakBySelesaiResp
	ReadKontrakResp
	UpdateKontrakReq
	ReadKontrakByMulaiReq
	ReadKontrakByMulaiResp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddKontrakReq struct {
	IdKontrak      string `protobuf:"bytes,1,opt,name=idKontrak" json:"idKontrak,omitempty"`
	TanggalMulai   string `protobuf:"bytes,2,opt,name=tanggalMulai" json:"tanggalMulai,omitempty"`
	TanggalSelesai string `protobuf:"bytes,3,opt,name=tanggalSelesai" json:"tanggalSelesai,omitempty"`
	Keterangan     string `protobuf:"bytes,4,opt,name=keterangan" json:"keterangan,omitempty"`
	Status         string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *AddKontrakReq) Reset()                    { *m = AddKontrakReq{} }
func (m *AddKontrakReq) String() string            { return proto.CompactTextString(m) }
func (*AddKontrakReq) ProtoMessage()               {}
func (*AddKontrakReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddKontrakReq) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *AddKontrakReq) GetTanggalMulai() string {
	if m != nil {
		return m.TanggalMulai
	}
	return ""
}

func (m *AddKontrakReq) GetTanggalSelesai() string {
	if m != nil {
		return m.TanggalSelesai
	}
	return ""
}

func (m *AddKontrakReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *AddKontrakReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadKontrakBySelesaiReq struct {
	TanggalSelesai string `protobuf:"bytes,1,opt,name=tanggalSelesai" json:"tanggalSelesai,omitempty"`
}

func (m *ReadKontrakBySelesaiReq) Reset()                    { *m = ReadKontrakBySelesaiReq{} }
func (m *ReadKontrakBySelesaiReq) String() string            { return proto.CompactTextString(m) }
func (*ReadKontrakBySelesaiReq) ProtoMessage()               {}
func (*ReadKontrakBySelesaiReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadKontrakBySelesaiReq) GetTanggalSelesai() string {
	if m != nil {
		return m.TanggalSelesai
	}
	return ""
}

type ReadKontrakBySelesaiResp struct {
	IdKontrak      string `protobuf:"bytes,1,opt,name=idKontrak" json:"idKontrak,omitempty"`
	TanggalMulai   string `protobuf:"bytes,2,opt,name=tanggalMulai" json:"tanggalMulai,omitempty"`
	TanggalSelesai string `protobuf:"bytes,3,opt,name=tanggalSelesai" json:"tanggalSelesai,omitempty"`
	Keterangan     string `protobuf:"bytes,4,opt,name=keterangan" json:"keterangan,omitempty"`
	Status         string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *ReadKontrakBySelesaiResp) Reset()                    { *m = ReadKontrakBySelesaiResp{} }
func (m *ReadKontrakBySelesaiResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKontrakBySelesaiResp) ProtoMessage()               {}
func (*ReadKontrakBySelesaiResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadKontrakBySelesaiResp) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *ReadKontrakBySelesaiResp) GetTanggalMulai() string {
	if m != nil {
		return m.TanggalMulai
	}
	return ""
}

func (m *ReadKontrakBySelesaiResp) GetTanggalSelesai() string {
	if m != nil {
		return m.TanggalSelesai
	}
	return ""
}

func (m *ReadKontrakBySelesaiResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *ReadKontrakBySelesaiResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadKontrakResp struct {
	AllKontrak []*ReadKontrakBySelesaiResp `protobuf:"bytes,1,rep,name=allKontrak" json:"allKontrak,omitempty"`
}

func (m *ReadKontrakResp) Reset()                    { *m = ReadKontrakResp{} }
func (m *ReadKontrakResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKontrakResp) ProtoMessage()               {}
func (*ReadKontrakResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadKontrakResp) GetAllKontrak() []*ReadKontrakBySelesaiResp {
	if m != nil {
		return m.AllKontrak
	}
	return nil
}

type UpdateKontrakReq struct {
	IdKontrak      string `protobuf:"bytes,1,opt,name=idKontrak" json:"idKontrak,omitempty"`
	TanggalMulai   string `protobuf:"bytes,2,opt,name=tanggalMulai" json:"tanggalMulai,omitempty"`
	TanggalSelesai string `protobuf:"bytes,3,opt,name=tanggalSelesai" json:"tanggalSelesai,omitempty"`
	Keterangan     string `protobuf:"bytes,4,opt,name=keterangan" json:"keterangan,omitempty"`
	Status         string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateKontrakReq) Reset()                    { *m = UpdateKontrakReq{} }
func (m *UpdateKontrakReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateKontrakReq) ProtoMessage()               {}
func (*UpdateKontrakReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateKontrakReq) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *UpdateKontrakReq) GetTanggalMulai() string {
	if m != nil {
		return m.TanggalMulai
	}
	return ""
}

func (m *UpdateKontrakReq) GetTanggalSelesai() string {
	if m != nil {
		return m.TanggalSelesai
	}
	return ""
}

func (m *UpdateKontrakReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *UpdateKontrakReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadKontrakByMulaiReq struct {
	TanggalMulai string `protobuf:"bytes,1,opt,name=tanggalMulai" json:"tanggalMulai,omitempty"`
}

func (m *ReadKontrakByMulaiReq) Reset()                    { *m = ReadKontrakByMulaiReq{} }
func (m *ReadKontrakByMulaiReq) String() string            { return proto.CompactTextString(m) }
func (*ReadKontrakByMulaiReq) ProtoMessage()               {}
func (*ReadKontrakByMulaiReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadKontrakByMulaiReq) GetTanggalMulai() string {
	if m != nil {
		return m.TanggalMulai
	}
	return ""
}

type ReadKontrakByMulaiResp struct {
	IdKontrak      string `protobuf:"bytes,1,opt,name=idKontrak" json:"idKontrak,omitempty"`
	TanggalMulai   string `protobuf:"bytes,2,opt,name=tanggalMulai" json:"tanggalMulai,omitempty"`
	TanggalSelesai string `protobuf:"bytes,3,opt,name=tanggalSelesai" json:"tanggalSelesai,omitempty"`
	Keterangan     string `protobuf:"bytes,4,opt,name=keterangan" json:"keterangan,omitempty"`
	Status         string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *ReadKontrakByMulaiResp) Reset()                    { *m = ReadKontrakByMulaiResp{} }
func (m *ReadKontrakByMulaiResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKontrakByMulaiResp) ProtoMessage()               {}
func (*ReadKontrakByMulaiResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadKontrakByMulaiResp) GetIdKontrak() string {
	if m != nil {
		return m.IdKontrak
	}
	return ""
}

func (m *ReadKontrakByMulaiResp) GetTanggalMulai() string {
	if m != nil {
		return m.TanggalMulai
	}
	return ""
}

func (m *ReadKontrakByMulaiResp) GetTanggalSelesai() string {
	if m != nil {
		return m.TanggalSelesai
	}
	return ""
}

func (m *ReadKontrakByMulaiResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *ReadKontrakByMulaiResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddKontrakReq)(nil), "grpc.AddKontrakReq")
	proto.RegisterType((*ReadKontrakBySelesaiReq)(nil), "grpc.ReadKontrakBySelesaiReq")
	proto.RegisterType((*ReadKontrakBySelesaiResp)(nil), "grpc.ReadKontrakBySelesaiResp")
	proto.RegisterType((*ReadKontrakResp)(nil), "grpc.ReadKontrakResp")
	proto.RegisterType((*UpdateKontrakReq)(nil), "grpc.UpdateKontrakReq")
	proto.RegisterType((*ReadKontrakByMulaiReq)(nil), "grpc.ReadKontrakByMulaiReq")
	proto.RegisterType((*ReadKontrakByMulaiResp)(nil), "grpc.ReadKontrakByMulaiResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for KontrakService service

type KontrakServiceClient interface {
	AddKontrak(ctx context.Context, in *AddKontrakReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadKontrakBySelesai(ctx context.Context, in *ReadKontrakBySelesaiReq, opts ...grpc1.CallOption) (*ReadKontrakBySelesaiResp, error)
	ReadKontrak(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKontrakResp, error)
	UpdateKontrak(ctx context.Context, in *UpdateKontrakReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadKontrakByMulai(ctx context.Context, in *ReadKontrakByMulaiReq, opts ...grpc1.CallOption) (*ReadKontrakByMulaiResp, error)
}

type kontrakServiceClient struct {
	cc *grpc1.ClientConn
}

func NewKontrakServiceClient(cc *grpc1.ClientConn) KontrakServiceClient {
	return &kontrakServiceClient{cc}
}

func (c *kontrakServiceClient) AddKontrak(ctx context.Context, in *AddKontrakReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KontrakService/AddKontrak", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kontrakServiceClient) ReadKontrakBySelesai(ctx context.Context, in *ReadKontrakBySelesaiReq, opts ...grpc1.CallOption) (*ReadKontrakBySelesaiResp, error) {
	out := new(ReadKontrakBySelesaiResp)
	err := grpc1.Invoke(ctx, "/grpc.KontrakService/ReadKontrakBySelesai", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kontrakServiceClient) ReadKontrak(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKontrakResp, error) {
	out := new(ReadKontrakResp)
	err := grpc1.Invoke(ctx, "/grpc.KontrakService/ReadKontrak", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kontrakServiceClient) UpdateKontrak(ctx context.Context, in *UpdateKontrakReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KontrakService/UpdateKontrak", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kontrakServiceClient) ReadKontrakByMulai(ctx context.Context, in *ReadKontrakByMulaiReq, opts ...grpc1.CallOption) (*ReadKontrakByMulaiResp, error) {
	out := new(ReadKontrakByMulaiResp)
	err := grpc1.Invoke(ctx, "/grpc.KontrakService/ReadKontrakByMulai", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KontrakService service

type KontrakServiceServer interface {
	AddKontrak(context.Context, *AddKontrakReq) (*google_protobuf.Empty, error)
	ReadKontrakBySelesai(context.Context, *ReadKontrakBySelesaiReq) (*ReadKontrakBySelesaiResp, error)
	ReadKontrak(context.Context, *google_protobuf.Empty) (*ReadKontrakResp, error)
	UpdateKontrak(context.Context, *UpdateKontrakReq) (*google_protobuf.Empty, error)
	ReadKontrakByMulai(context.Context, *ReadKontrakByMulaiReq) (*ReadKontrakByMulaiResp, error)
}

func RegisterKontrakServiceServer(s *grpc1.Server, srv KontrakServiceServer) {
	s.RegisterService(&_KontrakService_serviceDesc, srv)
}

func _KontrakService_AddKontrak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKontrakReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KontrakServiceServer).AddKontrak(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KontrakService/AddKontrak",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KontrakServiceServer).AddKontrak(ctx, req.(*AddKontrakReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KontrakService_ReadKontrakBySelesai_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKontrakBySelesaiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KontrakServiceServer).ReadKontrakBySelesai(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KontrakService/ReadKontrakBySelesai",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KontrakServiceServer).ReadKontrakBySelesai(ctx, req.(*ReadKontrakBySelesaiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KontrakService_ReadKontrak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KontrakServiceServer).ReadKontrak(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KontrakService/ReadKontrak",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KontrakServiceServer).ReadKontrak(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KontrakService_UpdateKontrak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKontrakReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KontrakServiceServer).UpdateKontrak(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KontrakService/UpdateKontrak",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KontrakServiceServer).UpdateKontrak(ctx, req.(*UpdateKontrakReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KontrakService_ReadKontrakByMulai_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKontrakByMulaiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KontrakServiceServer).ReadKontrakByMulai(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KontrakService/ReadKontrakByMulai",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KontrakServiceServer).ReadKontrakByMulai(ctx, req.(*ReadKontrakByMulaiReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _KontrakService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.KontrakService",
	HandlerType: (*KontrakServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddKontrak",
			Handler:    _KontrakService_AddKontrak_Handler,
		},
		{
			MethodName: "ReadKontrakBySelesai",
			Handler:    _KontrakService_ReadKontrakBySelesai_Handler,
		},
		{
			MethodName: "ReadKontrak",
			Handler:    _KontrakService_ReadKontrak_Handler,
		},
		{
			MethodName: "UpdateKontrak",
			Handler:    _KontrakService_UpdateKontrak_Handler,
		},
		{
			MethodName: "ReadKontrakByMulai",
			Handler:    _KontrakService_ReadKontrakByMulai_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "kontrak.proto",
}

func init() { proto.RegisterFile("kontrak.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0x1d, 0x75, 0x05, 0x9f, 0xab, 0xbb, 0xbc, 0x5d, 0x6d, 0x88, 0x56, 0xca, 0x1c, 0x8a,
	0xa7, 0x08, 0xf6, 0x28, 0x08, 0x16, 0x7a, 0x2a, 0x3d, 0x18, 0x29, 0x3d, 0x8f, 0x3a, 0x0d, 0xc1,
	0x34, 0x89, 0xc9, 0x58, 0xf0, 0xcf, 0x2a, 0xf4, 0x54, 0xfa, 0xa7, 0xf5, 0x50, 0x66, 0x92, 0x60,
	0x62, 0xa2, 0x3d, 0x7b, 0x7c, 0xbf, 0x3f, 0x2f, 0xf9, 0xce, 0x83, 0xe6, 0xda, 0x73, 0x45, 0xc0,
	0xd6, 0x86, 0x1f, 0x78, 0xc2, 0xc3, 0xaa, 0x15, 0xf8, 0x4b, 0xbd, 0x6b, 0x79, 0x9e, 0xe5, 0xf0,
	0xa1, 0xf2, 0x2d, 0xb6, 0xcf, 0x43, 0xfe, 0xe2, 0x8b, 0x5d, 0x94, 0x42, 0xdf, 0x08, 0x34, 0xa7,
	0xab, 0xd5, 0x7d, 0x54, 0x67, 0xf2, 0x0d, 0xf6, 0xa0, 0x6e, 0x27, 0xb6, 0x46, 0xae, 0xc8, 0xa0,
	0x6e, 0xee, 0x1d, 0x48, 0xe1, 0xb7, 0x60, 0xae, 0x65, 0x31, 0xe7, 0x61, 0xeb, 0x30, 0x5b, 0x2b,
	0xab, 0x84, 0x8c, 0x0f, 0xaf, 0xa1, 0x15, 0xdb, 0x73, 0xee, 0xf0, 0x90, 0xd9, 0x5a, 0x45, 0x65,
	0x1d, 0x78, 0xb1, 0x0f, 0xb0, 0xe6, 0x82, 0x07, 0xcc, 0xb5, 0x98, 0xab, 0x55, 0x55, 0x4e, 0xca,
	0x83, 0x1d, 0xa8, 0x85, 0x82, 0x89, 0x6d, 0xa8, 0xfd, 0x52, 0xb1, 0xd8, 0xa2, 0x53, 0xb8, 0x30,
	0x39, 0x4b, 0x90, 0x6e, 0x77, 0x71, 0x3f, 0x09, 0x9f, 0x1f, 0x4d, 0x8a, 0x46, 0xd3, 0x4f, 0x02,
	0x5a, 0x71, 0x8f, 0xd0, 0x3f, 0x83, 0x2f, 0x30, 0x83, 0x3f, 0x29, 0x7a, 0x05, 0x3d, 0x01, 0x60,
	0x8e, 0xb3, 0xa7, 0xae, 0x0c, 0x1a, 0xa3, 0xbe, 0x21, 0x05, 0x60, 0x1c, 0x5b, 0xd4, 0x4c, 0x55,
	0xd0, 0x77, 0x02, 0x7f, 0x1f, 0xfd, 0x15, 0x13, 0xfc, 0xac, 0xb4, 0x30, 0x86, 0x76, 0x66, 0x3d,
	0x35, 0x55, 0xa2, 0x1f, 0xc2, 0x91, 0x3c, 0x1c, 0xfd, 0x20, 0xd0, 0x29, 0xaa, 0x3e, 0x07, 0x0d,
	0x8c, 0xbe, 0xca, 0xd0, 0x8a, 0x79, 0xe6, 0x3c, 0x78, 0xb5, 0x97, 0x1c, 0xc7, 0x00, 0xfb, 0xb7,
	0x8c, 0xff, 0xa2, 0xbf, 0x9f, 0x79, 0xdd, 0x7a, 0xc7, 0x88, 0xae, 0x81, 0x91, 0x5c, 0x03, 0xe3,
	0x4e, 0x5e, 0x03, 0x5a, 0xc2, 0x27, 0xf8, 0x5f, 0x24, 0x14, 0xbc, 0x3c, 0x25, 0xa2, 0x8d, 0xfe,
	0x83, 0xc6, 0x68, 0x09, 0x27, 0xd0, 0x48, 0x45, 0xf1, 0x08, 0x81, 0xde, 0xce, 0x35, 0x8a, 0xeb,
	0xa7, 0xd0, 0xcc, 0x08, 0x53, 0x76, 0x90, 0x99, 0x87, 0x6a, 0x3d, 0xb1, 0xdb, 0x0c, 0x30, 0xff,
	0x9f, 0xb1, 0x5b, 0x80, 0x9e, 0xe8, 0x47, 0xef, 0x1d, 0x0f, 0x4a, 0xaa, 0x45, 0x4d, 0x0d, 0xb9,
	0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x15, 0x25, 0x81, 0x76, 0x73, 0x05, 0x00, 0x00,
}
