// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tamu.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	tamu.proto

It has these top-level messages:
	AddTamuReq
	ReadTamuByTeleponReq
	ReadTamuByTeleponResp
	ReadTamuResp
	UpdateTamuReq
	ReadTamuByNamaReq
	ReadTamuByNamaResp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddTamuReq struct {
	IdTamu       string `protobuf:"bytes,1,opt,name=idTamu" json:"idTamu,omitempty"`
	NamaTamu     string `protobuf:"bytes,2,opt,name=namaTamu" json:"namaTamu,omitempty"`
	NoTelepon    string `protobuf:"bytes,3,opt,name=noTelepon" json:"noTelepon,omitempty"`
	JenisKelamin string `protobuf:"bytes,4,opt,name=jenisKelamin" json:"jenisKelamin,omitempty"`
	IdAlamat     string `protobuf:"bytes,5,opt,name=idAlamat" json:"idAlamat,omitempty"`
	Status       string `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
}

func (m *AddTamuReq) Reset()                    { *m = AddTamuReq{} }
func (m *AddTamuReq) String() string            { return proto.CompactTextString(m) }
func (*AddTamuReq) ProtoMessage()               {}
func (*AddTamuReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddTamuReq) GetIdTamu() string {
	if m != nil {
		return m.IdTamu
	}
	return ""
}

func (m *AddTamuReq) GetNamaTamu() string {
	if m != nil {
		return m.NamaTamu
	}
	return ""
}

func (m *AddTamuReq) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *AddTamuReq) GetJenisKelamin() string {
	if m != nil {
		return m.JenisKelamin
	}
	return ""
}

func (m *AddTamuReq) GetIdAlamat() string {
	if m != nil {
		return m.IdAlamat
	}
	return ""
}

func (m *AddTamuReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadTamuByTeleponReq struct {
	NoTelepon string `protobuf:"bytes,1,opt,name=noTelepon" json:"noTelepon,omitempty"`
}

func (m *ReadTamuByTeleponReq) Reset()                    { *m = ReadTamuByTeleponReq{} }
func (m *ReadTamuByTeleponReq) String() string            { return proto.CompactTextString(m) }
func (*ReadTamuByTeleponReq) ProtoMessage()               {}
func (*ReadTamuByTeleponReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadTamuByTeleponReq) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

type ReadTamuByTeleponResp struct {
	IdTamu       string `protobuf:"bytes,1,opt,name=idTamu" json:"idTamu,omitempty"`
	NamaTamu     string `protobuf:"bytes,2,opt,name=namaTamu" json:"namaTamu,omitempty"`
	NoTelepon    string `protobuf:"bytes,3,opt,name=noTelepon" json:"noTelepon,omitempty"`
	JenisKelamin string `protobuf:"bytes,4,opt,name=jenisKelamin" json:"jenisKelamin,omitempty"`
	IdAlamat     string `protobuf:"bytes,5,opt,name=idAlamat" json:"idAlamat,omitempty"`
	Status       string `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
}

func (m *ReadTamuByTeleponResp) Reset()                    { *m = ReadTamuByTeleponResp{} }
func (m *ReadTamuByTeleponResp) String() string            { return proto.CompactTextString(m) }
func (*ReadTamuByTeleponResp) ProtoMessage()               {}
func (*ReadTamuByTeleponResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadTamuByTeleponResp) GetIdTamu() string {
	if m != nil {
		return m.IdTamu
	}
	return ""
}

func (m *ReadTamuByTeleponResp) GetNamaTamu() string {
	if m != nil {
		return m.NamaTamu
	}
	return ""
}

func (m *ReadTamuByTeleponResp) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *ReadTamuByTeleponResp) GetJenisKelamin() string {
	if m != nil {
		return m.JenisKelamin
	}
	return ""
}

func (m *ReadTamuByTeleponResp) GetIdAlamat() string {
	if m != nil {
		return m.IdAlamat
	}
	return ""
}

func (m *ReadTamuByTeleponResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadTamuResp struct {
	AllTamu []*ReadTamuByTeleponResp `protobuf:"bytes,1,rep,name=allTamu" json:"allTamu,omitempty"`
}

func (m *ReadTamuResp) Reset()                    { *m = ReadTamuResp{} }
func (m *ReadTamuResp) String() string            { return proto.CompactTextString(m) }
func (*ReadTamuResp) ProtoMessage()               {}
func (*ReadTamuResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadTamuResp) GetAllTamu() []*ReadTamuByTeleponResp {
	if m != nil {
		return m.AllTamu
	}
	return nil
}

type UpdateTamuReq struct {
	IdTamu       string `protobuf:"bytes,1,opt,name=idTamu" json:"idTamu,omitempty"`
	NamaTamu     string `protobuf:"bytes,2,opt,name=namaTamu" json:"namaTamu,omitempty"`
	NoTelepon    string `protobuf:"bytes,3,opt,name=noTelepon" json:"noTelepon,omitempty"`
	JenisKelamin string `protobuf:"bytes,4,opt,name=jenisKelamin" json:"jenisKelamin,omitempty"`
	IdAlamat     string `protobuf:"bytes,5,opt,name=idAlamat" json:"idAlamat,omitempty"`
	Status       string `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateTamuReq) Reset()                    { *m = UpdateTamuReq{} }
func (m *UpdateTamuReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateTamuReq) ProtoMessage()               {}
func (*UpdateTamuReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateTamuReq) GetIdTamu() string {
	if m != nil {
		return m.IdTamu
	}
	return ""
}

func (m *UpdateTamuReq) GetNamaTamu() string {
	if m != nil {
		return m.NamaTamu
	}
	return ""
}

func (m *UpdateTamuReq) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *UpdateTamuReq) GetJenisKelamin() string {
	if m != nil {
		return m.JenisKelamin
	}
	return ""
}

func (m *UpdateTamuReq) GetIdAlamat() string {
	if m != nil {
		return m.IdAlamat
	}
	return ""
}

func (m *UpdateTamuReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadTamuByNamaReq struct {
	NamaTamu string `protobuf:"bytes,1,opt,name=namaTamu" json:"namaTamu,omitempty"`
}

func (m *ReadTamuByNamaReq) Reset()                    { *m = ReadTamuByNamaReq{} }
func (m *ReadTamuByNamaReq) String() string            { return proto.CompactTextString(m) }
func (*ReadTamuByNamaReq) ProtoMessage()               {}
func (*ReadTamuByNamaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadTamuByNamaReq) GetNamaTamu() string {
	if m != nil {
		return m.NamaTamu
	}
	return ""
}

type ReadTamuByNamaResp struct {
	IdTamu       string `protobuf:"bytes,1,opt,name=idTamu" json:"idTamu,omitempty"`
	NamaTamu     string `protobuf:"bytes,2,opt,name=namaTamu" json:"namaTamu,omitempty"`
	NoTelepon    string `protobuf:"bytes,3,opt,name=noTelepon" json:"noTelepon,omitempty"`
	JenisKelamin string `protobuf:"bytes,4,opt,name=jenisKelamin" json:"jenisKelamin,omitempty"`
	IdAlamat     string `protobuf:"bytes,5,opt,name=idAlamat" json:"idAlamat,omitempty"`
	Status       string `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
}

func (m *ReadTamuByNamaResp) Reset()                    { *m = ReadTamuByNamaResp{} }
func (m *ReadTamuByNamaResp) String() string            { return proto.CompactTextString(m) }
func (*ReadTamuByNamaResp) ProtoMessage()               {}
func (*ReadTamuByNamaResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadTamuByNamaResp) GetIdTamu() string {
	if m != nil {
		return m.IdTamu
	}
	return ""
}

func (m *ReadTamuByNamaResp) GetNamaTamu() string {
	if m != nil {
		return m.NamaTamu
	}
	return ""
}

func (m *ReadTamuByNamaResp) GetNoTelepon() string {
	if m != nil {
		return m.NoTelepon
	}
	return ""
}

func (m *ReadTamuByNamaResp) GetJenisKelamin() string {
	if m != nil {
		return m.JenisKelamin
	}
	return ""
}

func (m *ReadTamuByNamaResp) GetIdAlamat() string {
	if m != nil {
		return m.IdAlamat
	}
	return ""
}

func (m *ReadTamuByNamaResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddTamuReq)(nil), "grpc.AddTamuReq")
	proto.RegisterType((*ReadTamuByTeleponReq)(nil), "grpc.ReadTamuByTeleponReq")
	proto.RegisterType((*ReadTamuByTeleponResp)(nil), "grpc.ReadTamuByTeleponResp")
	proto.RegisterType((*ReadTamuResp)(nil), "grpc.ReadTamuResp")
	proto.RegisterType((*UpdateTamuReq)(nil), "grpc.UpdateTamuReq")
	proto.RegisterType((*ReadTamuByNamaReq)(nil), "grpc.ReadTamuByNamaReq")
	proto.RegisterType((*ReadTamuByNamaResp)(nil), "grpc.ReadTamuByNamaResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for TamuService service

type TamuServiceClient interface {
	AddTamu(ctx context.Context, in *AddTamuReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadTamuByTelepon(ctx context.Context, in *ReadTamuByTeleponReq, opts ...grpc1.CallOption) (*ReadTamuByTeleponResp, error)
	ReadTamu(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadTamuResp, error)
	UpdateTamu(ctx context.Context, in *UpdateTamuReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadTamuByNama(ctx context.Context, in *ReadTamuByNamaReq, opts ...grpc1.CallOption) (*ReadTamuByNamaResp, error)
}

type tamuServiceClient struct {
	cc *grpc1.ClientConn
}

func NewTamuServiceClient(cc *grpc1.ClientConn) TamuServiceClient {
	return &tamuServiceClient{cc}
}

func (c *tamuServiceClient) AddTamu(ctx context.Context, in *AddTamuReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.TamuService/AddTamu", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tamuServiceClient) ReadTamuByTelepon(ctx context.Context, in *ReadTamuByTeleponReq, opts ...grpc1.CallOption) (*ReadTamuByTeleponResp, error) {
	out := new(ReadTamuByTeleponResp)
	err := grpc1.Invoke(ctx, "/grpc.TamuService/ReadTamuByTelepon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tamuServiceClient) ReadTamu(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadTamuResp, error) {
	out := new(ReadTamuResp)
	err := grpc1.Invoke(ctx, "/grpc.TamuService/ReadTamu", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tamuServiceClient) UpdateTamu(ctx context.Context, in *UpdateTamuReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.TamuService/UpdateTamu", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tamuServiceClient) ReadTamuByNama(ctx context.Context, in *ReadTamuByNamaReq, opts ...grpc1.CallOption) (*ReadTamuByNamaResp, error) {
	out := new(ReadTamuByNamaResp)
	err := grpc1.Invoke(ctx, "/grpc.TamuService/ReadTamuByNama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TamuService service

type TamuServiceServer interface {
	AddTamu(context.Context, *AddTamuReq) (*google_protobuf.Empty, error)
	ReadTamuByTelepon(context.Context, *ReadTamuByTeleponReq) (*ReadTamuByTeleponResp, error)
	ReadTamu(context.Context, *google_protobuf.Empty) (*ReadTamuResp, error)
	UpdateTamu(context.Context, *UpdateTamuReq) (*google_protobuf.Empty, error)
	ReadTamuByNama(context.Context, *ReadTamuByNamaReq) (*ReadTamuByNamaResp, error)
}

func RegisterTamuServiceServer(s *grpc1.Server, srv TamuServiceServer) {
	s.RegisterService(&_TamuService_serviceDesc, srv)
}

func _TamuService_AddTamu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTamuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TamuServiceServer).AddTamu(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TamuService/AddTamu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TamuServiceServer).AddTamu(ctx, req.(*AddTamuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TamuService_ReadTamuByTelepon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTamuByTeleponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TamuServiceServer).ReadTamuByTelepon(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TamuService/ReadTamuByTelepon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TamuServiceServer).ReadTamuByTelepon(ctx, req.(*ReadTamuByTeleponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TamuService_ReadTamu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TamuServiceServer).ReadTamu(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TamuService/ReadTamu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TamuServiceServer).ReadTamu(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TamuService_UpdateTamu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTamuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TamuServiceServer).UpdateTamu(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TamuService/UpdateTamu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TamuServiceServer).UpdateTamu(ctx, req.(*UpdateTamuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TamuService_ReadTamuByNama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTamuByNamaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TamuServiceServer).ReadTamuByNama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TamuService/ReadTamuByNama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TamuServiceServer).ReadTamuByNama(ctx, req.(*ReadTamuByNamaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TamuService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.TamuService",
	HandlerType: (*TamuServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddTamu",
			Handler:    _TamuService_AddTamu_Handler,
		},
		{
			MethodName: "ReadTamuByTelepon",
			Handler:    _TamuService_ReadTamuByTelepon_Handler,
		},
		{
			MethodName: "ReadTamu",
			Handler:    _TamuService_ReadTamu_Handler,
		},
		{
			MethodName: "UpdateTamu",
			Handler:    _TamuService_UpdateTamu_Handler,
		},
		{
			MethodName: "ReadTamuByNama",
			Handler:    _TamuService_ReadTamuByNama_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "tamu.proto",
}

func init() { proto.RegisterFile("tamu.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0x59, 0xe0, 0xe3, 0x83, 0x01, 0x8d, 0xae, 0x8a, 0xcd, 0xe2, 0xc1, 0xec, 0x89, 0x53,
	0x49, 0x50, 0x13, 0x13, 0x4f, 0x98, 0x70, 0x32, 0xe1, 0x50, 0xf1, 0x01, 0x16, 0xba, 0x92, 0x9a,
	0x6e, 0x5b, 0xe8, 0xd6, 0x84, 0x17, 0x33, 0xf1, 0x62, 0xe2, 0x2b, 0xf8, 0x44, 0x66, 0x77, 0x5b,
	0x4b, 0x09, 0x70, 0xef, 0x71, 0x76, 0x66, 0x67, 0x7f, 0xff, 0xfd, 0xcf, 0x00, 0x48, 0x26, 0x12,
	0x3b, 0x5a, 0x85, 0x32, 0xc4, 0xf5, 0xc5, 0x2a, 0x9a, 0x93, 0xde, 0x22, 0x0c, 0x17, 0x3e, 0x1f,
	0xe8, 0xb3, 0x59, 0xf2, 0x3a, 0xe0, 0x22, 0x92, 0x6b, 0x53, 0x42, 0x3f, 0x10, 0xc0, 0xc8, 0x75,
	0xa7, 0x4c, 0x24, 0x0e, 0x5f, 0xe2, 0x2e, 0x34, 0x3c, 0x1d, 0x58, 0xe8, 0x1a, 0xf5, 0x5b, 0x4e,
	0x1a, 0x61, 0x02, 0xcd, 0x80, 0x09, 0xa6, 0x33, 0x55, 0x9d, 0xf9, 0x8b, 0xf1, 0x15, 0xb4, 0x82,
	0x70, 0xca, 0x7d, 0x1e, 0x85, 0x81, 0x55, 0xd3, 0xc9, 0xfc, 0x00, 0x53, 0xe8, 0xbc, 0xf1, 0xc0,
	0x8b, 0x9f, 0xb8, 0xcf, 0x84, 0x17, 0x58, 0x75, 0x5d, 0x50, 0x38, 0x53, 0xdd, 0x3d, 0x77, 0xe4,
	0x33, 0xc1, 0xa4, 0xf5, 0xcf, 0x74, 0xcf, 0x62, 0x45, 0x14, 0x4b, 0x26, 0x93, 0xd8, 0x6a, 0x18,
	0x22, 0x13, 0xd1, 0x5b, 0x38, 0x77, 0x38, 0xd3, 0x74, 0x8f, 0xeb, 0xf4, 0x31, 0xa5, 0xa0, 0x40,
	0x83, 0xb6, 0x68, 0xe8, 0x37, 0x82, 0x8b, 0x1d, 0xd7, 0xe2, 0xa8, 0x44, 0xca, 0xc7, 0xd0, 0xc9,
	0x24, 0x68, 0xf2, 0x3b, 0xf8, 0xcf, 0x7c, 0x3f, 0x45, 0xaf, 0xf5, 0xdb, 0xc3, 0x9e, 0xad, 0x7c,
	0xb7, 0x77, 0xea, 0x74, 0xb2, 0x5a, 0xfa, 0x89, 0xe0, 0xe8, 0x25, 0x72, 0x99, 0xe4, 0xe5, 0x33,
	0x7f, 0x00, 0xa7, 0xb9, 0xba, 0x09, 0x13, 0x4c, 0xe1, 0x6f, 0x62, 0xa2, 0x22, 0x26, 0xfd, 0x42,
	0x80, 0xb7, 0x6f, 0x94, 0xc9, 0xf4, 0xe1, 0x4f, 0x15, 0xda, 0xea, 0xf9, 0x67, 0xbe, 0x7a, 0xf7,
	0xe6, 0x5c, 0x99, 0x9e, 0xae, 0x2d, 0x3e, 0x31, 0x76, 0xe7, 0x5b, 0x4c, 0xba, 0xb6, 0x59, 0x79,
	0x3b, 0x5b, 0x79, 0x7b, 0xac, 0x56, 0x9e, 0x56, 0xf0, 0x64, 0xf3, 0xe3, 0x32, 0x66, 0xb2, 0x77,
	0x5e, 0x96, 0xe4, 0xd0, 0x2c, 0xd1, 0x0a, 0xbe, 0x87, 0x66, 0x96, 0xc2, 0x7b, 0x5e, 0x25, 0xb8,
	0xd8, 0x22, 0xbd, 0xf9, 0x00, 0x90, 0x4f, 0x1f, 0x3e, 0x33, 0x35, 0x85, 0x79, 0x3c, 0x20, 0x63,
	0x0c, 0xc7, 0x45, 0x37, 0xf1, 0xe5, 0x36, 0x67, 0x3a, 0x15, 0xc4, 0xda, 0x9d, 0x50, 0x0c, 0xb3,
	0x86, 0x6e, 0x7c, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x77, 0xcb, 0x52, 0x34, 0x05, 0x00,
	0x00,
}
