// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alamat.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	alamat.proto

It has these top-level messages:
	AddAlamatReq
	ReadAlamatByNoRumahReq
	ReadAlamatByNoRumahResp
	ReadAlamatResp
	UpdateAlamatReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddAlamatReq struct {
	IdAlamat    string `protobuf:"bytes,1,opt,name=idAlamat" json:"idAlamat,omitempty"`
	AlamatRumah string `protobuf:"bytes,2,opt,name=alamatRumah" json:"alamatRumah,omitempty"`
	RtRw        string `protobuf:"bytes,3,opt,name=rtRw" json:"rtRw,omitempty"`
	NoRumah     string `protobuf:"bytes,4,opt,name=noRumah" json:"noRumah,omitempty"`
	IdKota      string `protobuf:"bytes,5,opt,name=idKota" json:"idKota,omitempty"`
	IdNegara    string `protobuf:"bytes,6,opt,name=idNegara" json:"idNegara,omitempty"`
	Status      string `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *AddAlamatReq) Reset()                    { *m = AddAlamatReq{} }
func (m *AddAlamatReq) String() string            { return proto.CompactTextString(m) }
func (*AddAlamatReq) ProtoMessage()               {}
func (*AddAlamatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddAlamatReq) GetIdAlamat() string {
	if m != nil {
		return m.IdAlamat
	}
	return ""
}

func (m *AddAlamatReq) GetAlamatRumah() string {
	if m != nil {
		return m.AlamatRumah
	}
	return ""
}

func (m *AddAlamatReq) GetRtRw() string {
	if m != nil {
		return m.RtRw
	}
	return ""
}

func (m *AddAlamatReq) GetNoRumah() string {
	if m != nil {
		return m.NoRumah
	}
	return ""
}

func (m *AddAlamatReq) GetIdKota() string {
	if m != nil {
		return m.IdKota
	}
	return ""
}

func (m *AddAlamatReq) GetIdNegara() string {
	if m != nil {
		return m.IdNegara
	}
	return ""
}

func (m *AddAlamatReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadAlamatByNoRumahReq struct {
	NoRumah string `protobuf:"bytes,1,opt,name=noRumah" json:"noRumah,omitempty"`
}

func (m *ReadAlamatByNoRumahReq) Reset()                    { *m = ReadAlamatByNoRumahReq{} }
func (m *ReadAlamatByNoRumahReq) String() string            { return proto.CompactTextString(m) }
func (*ReadAlamatByNoRumahReq) ProtoMessage()               {}
func (*ReadAlamatByNoRumahReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadAlamatByNoRumahReq) GetNoRumah() string {
	if m != nil {
		return m.NoRumah
	}
	return ""
}

type ReadAlamatByNoRumahResp struct {
	IdAlamat    string `protobuf:"bytes,1,opt,name=idAlamat" json:"idAlamat,omitempty"`
	AlamatRumah string `protobuf:"bytes,2,opt,name=alamatRumah" json:"alamatRumah,omitempty"`
	RtRw        string `protobuf:"bytes,3,opt,name=rtRw" json:"rtRw,omitempty"`
	NoRumah     string `protobuf:"bytes,4,opt,name=noRumah" json:"noRumah,omitempty"`
	IdKota      string `protobuf:"bytes,5,opt,name=idKota" json:"idKota,omitempty"`
	IdNegara    string `protobuf:"bytes,6,opt,name=idNegara" json:"idNegara,omitempty"`
	Status      string `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *ReadAlamatByNoRumahResp) Reset()                    { *m = ReadAlamatByNoRumahResp{} }
func (m *ReadAlamatByNoRumahResp) String() string            { return proto.CompactTextString(m) }
func (*ReadAlamatByNoRumahResp) ProtoMessage()               {}
func (*ReadAlamatByNoRumahResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadAlamatByNoRumahResp) GetIdAlamat() string {
	if m != nil {
		return m.IdAlamat
	}
	return ""
}

func (m *ReadAlamatByNoRumahResp) GetAlamatRumah() string {
	if m != nil {
		return m.AlamatRumah
	}
	return ""
}

func (m *ReadAlamatByNoRumahResp) GetRtRw() string {
	if m != nil {
		return m.RtRw
	}
	return ""
}

func (m *ReadAlamatByNoRumahResp) GetNoRumah() string {
	if m != nil {
		return m.NoRumah
	}
	return ""
}

func (m *ReadAlamatByNoRumahResp) GetIdKota() string {
	if m != nil {
		return m.IdKota
	}
	return ""
}

func (m *ReadAlamatByNoRumahResp) GetIdNegara() string {
	if m != nil {
		return m.IdNegara
	}
	return ""
}

func (m *ReadAlamatByNoRumahResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadAlamatResp struct {
	AllAlamat []*ReadAlamatByNoRumahResp `protobuf:"bytes,1,rep,name=allAlamat" json:"allAlamat,omitempty"`
}

func (m *ReadAlamatResp) Reset()                    { *m = ReadAlamatResp{} }
func (m *ReadAlamatResp) String() string            { return proto.CompactTextString(m) }
func (*ReadAlamatResp) ProtoMessage()               {}
func (*ReadAlamatResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadAlamatResp) GetAllAlamat() []*ReadAlamatByNoRumahResp {
	if m != nil {
		return m.AllAlamat
	}
	return nil
}

type UpdateAlamatReq struct {
	IdAlamat    string `protobuf:"bytes,1,opt,name=idAlamat" json:"idAlamat,omitempty"`
	AlamatRumah string `protobuf:"bytes,2,opt,name=alamatRumah" json:"alamatRumah,omitempty"`
	RtRw        string `protobuf:"bytes,3,opt,name=rtRw" json:"rtRw,omitempty"`
	NoRumah     string `protobuf:"bytes,4,opt,name=noRumah" json:"noRumah,omitempty"`
	IdKota      string `protobuf:"bytes,5,opt,name=idKota" json:"idKota,omitempty"`
	IdNegara    string `protobuf:"bytes,6,opt,name=idNegara" json:"idNegara,omitempty"`
	Status      string `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateAlamatReq) Reset()                    { *m = UpdateAlamatReq{} }
func (m *UpdateAlamatReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateAlamatReq) ProtoMessage()               {}
func (*UpdateAlamatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateAlamatReq) GetIdAlamat() string {
	if m != nil {
		return m.IdAlamat
	}
	return ""
}

func (m *UpdateAlamatReq) GetAlamatRumah() string {
	if m != nil {
		return m.AlamatRumah
	}
	return ""
}

func (m *UpdateAlamatReq) GetRtRw() string {
	if m != nil {
		return m.RtRw
	}
	return ""
}

func (m *UpdateAlamatReq) GetNoRumah() string {
	if m != nil {
		return m.NoRumah
	}
	return ""
}

func (m *UpdateAlamatReq) GetIdKota() string {
	if m != nil {
		return m.IdKota
	}
	return ""
}

func (m *UpdateAlamatReq) GetIdNegara() string {
	if m != nil {
		return m.IdNegara
	}
	return ""
}

func (m *UpdateAlamatReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddAlamatReq)(nil), "grpc.AddAlamatReq")
	proto.RegisterType((*ReadAlamatByNoRumahReq)(nil), "grpc.ReadAlamatByNoRumahReq")
	proto.RegisterType((*ReadAlamatByNoRumahResp)(nil), "grpc.ReadAlamatByNoRumahResp")
	proto.RegisterType((*ReadAlamatResp)(nil), "grpc.ReadAlamatResp")
	proto.RegisterType((*UpdateAlamatReq)(nil), "grpc.UpdateAlamatReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for AlamatService service

type AlamatServiceClient interface {
	AddAlamat(ctx context.Context, in *AddAlamatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadAlamatByNoRumah(ctx context.Context, in *ReadAlamatByNoRumahReq, opts ...grpc1.CallOption) (*ReadAlamatByNoRumahResp, error)
	ReadAlamat(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadAlamatResp, error)
	UpdateAlamat(ctx context.Context, in *UpdateAlamatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type alamatServiceClient struct {
	cc *grpc1.ClientConn
}

func NewAlamatServiceClient(cc *grpc1.ClientConn) AlamatServiceClient {
	return &alamatServiceClient{cc}
}

func (c *alamatServiceClient) AddAlamat(ctx context.Context, in *AddAlamatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AlamatService/AddAlamat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alamatServiceClient) ReadAlamatByNoRumah(ctx context.Context, in *ReadAlamatByNoRumahReq, opts ...grpc1.CallOption) (*ReadAlamatByNoRumahResp, error) {
	out := new(ReadAlamatByNoRumahResp)
	err := grpc1.Invoke(ctx, "/grpc.AlamatService/ReadAlamatByNoRumah", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alamatServiceClient) ReadAlamat(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadAlamatResp, error) {
	out := new(ReadAlamatResp)
	err := grpc1.Invoke(ctx, "/grpc.AlamatService/ReadAlamat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alamatServiceClient) UpdateAlamat(ctx context.Context, in *UpdateAlamatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AlamatService/UpdateAlamat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AlamatService service

type AlamatServiceServer interface {
	AddAlamat(context.Context, *AddAlamatReq) (*google_protobuf.Empty, error)
	ReadAlamatByNoRumah(context.Context, *ReadAlamatByNoRumahReq) (*ReadAlamatByNoRumahResp, error)
	ReadAlamat(context.Context, *google_protobuf.Empty) (*ReadAlamatResp, error)
	UpdateAlamat(context.Context, *UpdateAlamatReq) (*google_protobuf.Empty, error)
}

func RegisterAlamatServiceServer(s *grpc1.Server, srv AlamatServiceServer) {
	s.RegisterService(&_AlamatService_serviceDesc, srv)
}

func _AlamatService_AddAlamat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAlamatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlamatServiceServer).AddAlamat(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlamatService/AddAlamat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlamatServiceServer).AddAlamat(ctx, req.(*AddAlamatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlamatService_ReadAlamatByNoRumah_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAlamatByNoRumahReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlamatServiceServer).ReadAlamatByNoRumah(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlamatService/ReadAlamatByNoRumah",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlamatServiceServer).ReadAlamatByNoRumah(ctx, req.(*ReadAlamatByNoRumahReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlamatService_ReadAlamat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlamatServiceServer).ReadAlamat(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlamatService/ReadAlamat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlamatServiceServer).ReadAlamat(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlamatService_UpdateAlamat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlamatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlamatServiceServer).UpdateAlamat(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlamatService/UpdateAlamat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlamatServiceServer).UpdateAlamat(ctx, req.(*UpdateAlamatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlamatService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.AlamatService",
	HandlerType: (*AlamatServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddAlamat",
			Handler:    _AlamatService_AddAlamat_Handler,
		},
		{
			MethodName: "ReadAlamatByNoRumah",
			Handler:    _AlamatService_ReadAlamatByNoRumah_Handler,
		},
		{
			MethodName: "ReadAlamat",
			Handler:    _AlamatService_ReadAlamat_Handler,
		},
		{
			MethodName: "UpdateAlamat",
			Handler:    _AlamatService_UpdateAlamat_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "alamat.proto",
}

func init() { proto.RegisterFile("alamat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xa6, 0xc0, 0x0f, 0x3f, 0x03, 0x6a, 0x32, 0x2a, 0x6e, 0xaa, 0x26, 0xa4, 0x27, 0x4e, 0x4b,
	0x82, 0x27, 0xa3, 0x89, 0xc1, 0xc4, 0x93, 0x91, 0xc3, 0xaa, 0x0f, 0xb0, 0xd0, 0xb5, 0x92, 0x14,
	0xb7, 0x94, 0x45, 0xc3, 0xd3, 0xf8, 0x36, 0x26, 0x1e, 0x7d, 0x23, 0xd3, 0x9d, 0x02, 0x95, 0x50,
	0xee, 0xdc, 0xfa, 0xcd, 0xcc, 0xd7, 0x99, 0xef, 0xdb, 0x19, 0x68, 0xc8, 0x50, 0x8e, 0xa5, 0xe1,
	0x51, 0xac, 0x8d, 0xc6, 0x72, 0x10, 0x47, 0x43, 0xf7, 0x34, 0xd0, 0x3a, 0x08, 0x55, 0xc7, 0xc6,
	0x06, 0xb3, 0x97, 0x8e, 0x1a, 0x47, 0x66, 0x4e, 0x25, 0xde, 0x97, 0x03, 0x8d, 0x9e, 0xef, 0xf7,
	0x2c, 0x4d, 0xa8, 0x09, 0xba, 0xf0, 0x7f, 0x94, 0x42, 0xe6, 0xb4, 0x9c, 0x76, 0x4d, 0x2c, 0x31,
	0xb6, 0xa0, 0x4e, 0xff, 0x17, 0xb3, 0xb1, 0x7c, 0x65, 0x45, 0x9b, 0xce, 0x86, 0x10, 0xa1, 0x1c,
	0x1b, 0xf1, 0xc1, 0x4a, 0x36, 0x65, 0xbf, 0x91, 0x41, 0xf5, 0x4d, 0x13, 0xa3, 0x6c, 0xc3, 0x0b,
	0x88, 0x4d, 0xa8, 0x8c, 0xfc, 0x7b, 0x6d, 0x24, 0xfb, 0x67, 0x13, 0x29, 0xa2, 0x19, 0xfa, 0x2a,
	0x90, 0xb1, 0x64, 0x95, 0xc5, 0x0c, 0x84, 0x13, 0xce, 0xd4, 0x48, 0x33, 0x9b, 0xb2, 0x2a, 0x71,
	0x08, 0x79, 0x5d, 0x68, 0x0a, 0x25, 0xd3, 0x49, 0x6f, 0xe7, 0x7d, 0x6a, 0x91, 0x28, 0xca, 0xf4,
	0x77, 0xfe, 0xf4, 0xf7, 0x7e, 0x1c, 0x38, 0xd9, 0x48, 0x9a, 0x46, 0x3b, 0xeb, 0xc3, 0x03, 0xec,
	0xaf, 0x24, 0x59, 0x25, 0x57, 0x50, 0x93, 0x61, 0xb8, 0x94, 0x52, 0x6a, 0xd7, 0xbb, 0xe7, 0x3c,
	0xd9, 0x0c, 0x9e, 0xa3, 0x5d, 0xac, 0xea, 0xbd, 0x6f, 0x07, 0x0e, 0x9e, 0x23, 0x5f, 0x1a, 0xb5,
	0xf3, 0x2b, 0xd2, 0xfd, 0x2c, 0xc2, 0x1e, 0x8d, 0xf9, 0xa8, 0xe2, 0xf7, 0xd1, 0x50, 0xe1, 0x25,
	0xd4, 0x96, 0xcb, 0x8f, 0x48, 0xa6, 0x64, 0xaf, 0xc1, 0x6d, 0x72, 0x3a, 0x1e, 0xbe, 0x38, 0x1e,
	0x7e, 0x97, 0x1c, 0x8f, 0x57, 0xc0, 0x27, 0x38, 0xdc, 0x60, 0x1f, 0x9e, 0x6d, 0x71, 0x76, 0xe2,
	0x6e, 0xf7, 0xdd, 0x2b, 0xe0, 0x35, 0xc0, 0x2a, 0x89, 0x39, 0xdd, 0xdd, 0xa3, 0xf5, 0xdf, 0xa4,
	0xec, 0x1b, 0x68, 0x64, 0xdf, 0x0a, 0x8f, 0xa9, 0x6e, 0xed, 0xfd, 0xf2, 0x45, 0x0d, 0x2a, 0x36,
	0x72, 0xf1, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xeb, 0x5b, 0x85, 0x47, 0x04, 0x00, 0x00,
}
