// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jenisPembayaran.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	jenisPembayaran.proto

It has these top-level messages:
	AddJenisPembayaranReq
	ReadJenisPembayaranByMetodeReq
	ReadJenisPembayaranByMetodeResp
	ReadJenisPembayaranResp
	UpdateJenisPembayaranReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddJenisPembayaranReq struct {
	IdJenisPembayaran string `protobuf:"bytes,1,opt,name=idJenisPembayaran" json:"idJenisPembayaran,omitempty"`
	MetodePembayaran  string `protobuf:"bytes,2,opt,name=metodePembayaran" json:"metodePembayaran,omitempty"`
	Status            string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *AddJenisPembayaranReq) Reset()                    { *m = AddJenisPembayaranReq{} }
func (m *AddJenisPembayaranReq) String() string            { return proto.CompactTextString(m) }
func (*AddJenisPembayaranReq) ProtoMessage()               {}
func (*AddJenisPembayaranReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddJenisPembayaranReq) GetIdJenisPembayaran() string {
	if m != nil {
		return m.IdJenisPembayaran
	}
	return ""
}

func (m *AddJenisPembayaranReq) GetMetodePembayaran() string {
	if m != nil {
		return m.MetodePembayaran
	}
	return ""
}

func (m *AddJenisPembayaranReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadJenisPembayaranByMetodeReq struct {
	MetodePembayaran string `protobuf:"bytes,1,opt,name=metodePembayaran" json:"metodePembayaran,omitempty"`
}

func (m *ReadJenisPembayaranByMetodeReq) Reset()                    { *m = ReadJenisPembayaranByMetodeReq{} }
func (m *ReadJenisPembayaranByMetodeReq) String() string            { return proto.CompactTextString(m) }
func (*ReadJenisPembayaranByMetodeReq) ProtoMessage()               {}
func (*ReadJenisPembayaranByMetodeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadJenisPembayaranByMetodeReq) GetMetodePembayaran() string {
	if m != nil {
		return m.MetodePembayaran
	}
	return ""
}

type ReadJenisPembayaranByMetodeResp struct {
	IdJenisPembayaran string `protobuf:"bytes,1,opt,name=idJenisPembayaran" json:"idJenisPembayaran,omitempty"`
	MetodePembayaran  string `protobuf:"bytes,2,opt,name=metodePembayaran" json:"metodePembayaran,omitempty"`
	Status            string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *ReadJenisPembayaranByMetodeResp) Reset()                    { *m = ReadJenisPembayaranByMetodeResp{} }
func (m *ReadJenisPembayaranByMetodeResp) String() string            { return proto.CompactTextString(m) }
func (*ReadJenisPembayaranByMetodeResp) ProtoMessage()               {}
func (*ReadJenisPembayaranByMetodeResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadJenisPembayaranByMetodeResp) GetIdJenisPembayaran() string {
	if m != nil {
		return m.IdJenisPembayaran
	}
	return ""
}

func (m *ReadJenisPembayaranByMetodeResp) GetMetodePembayaran() string {
	if m != nil {
		return m.MetodePembayaran
	}
	return ""
}

func (m *ReadJenisPembayaranByMetodeResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadJenisPembayaranResp struct {
	AllJenisPembayaran []*ReadJenisPembayaranByMetodeResp `protobuf:"bytes,1,rep,name=allJenisPembayaran" json:"allJenisPembayaran,omitempty"`
}

func (m *ReadJenisPembayaranResp) Reset()                    { *m = ReadJenisPembayaranResp{} }
func (m *ReadJenisPembayaranResp) String() string            { return proto.CompactTextString(m) }
func (*ReadJenisPembayaranResp) ProtoMessage()               {}
func (*ReadJenisPembayaranResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadJenisPembayaranResp) GetAllJenisPembayaran() []*ReadJenisPembayaranByMetodeResp {
	if m != nil {
		return m.AllJenisPembayaran
	}
	return nil
}

type UpdateJenisPembayaranReq struct {
	IdJenisPembayaran string `protobuf:"bytes,1,opt,name=idJenisPembayaran" json:"idJenisPembayaran,omitempty"`
	MetodePembayaran  string `protobuf:"bytes,2,opt,name=metodePembayaran" json:"metodePembayaran,omitempty"`
	Status            string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateJenisPembayaranReq) Reset()                    { *m = UpdateJenisPembayaranReq{} }
func (m *UpdateJenisPembayaranReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateJenisPembayaranReq) ProtoMessage()               {}
func (*UpdateJenisPembayaranReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateJenisPembayaranReq) GetIdJenisPembayaran() string {
	if m != nil {
		return m.IdJenisPembayaran
	}
	return ""
}

func (m *UpdateJenisPembayaranReq) GetMetodePembayaran() string {
	if m != nil {
		return m.MetodePembayaran
	}
	return ""
}

func (m *UpdateJenisPembayaranReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddJenisPembayaranReq)(nil), "grpc.AddJenisPembayaranReq")
	proto.RegisterType((*ReadJenisPembayaranByMetodeReq)(nil), "grpc.ReadJenisPembayaranByMetodeReq")
	proto.RegisterType((*ReadJenisPembayaranByMetodeResp)(nil), "grpc.ReadJenisPembayaranByMetodeResp")
	proto.RegisterType((*ReadJenisPembayaranResp)(nil), "grpc.ReadJenisPembayaranResp")
	proto.RegisterType((*UpdateJenisPembayaranReq)(nil), "grpc.UpdateJenisPembayaranReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for JenisPembayaranService service

type JenisPembayaranServiceClient interface {
	AddJenisPembayaran(ctx context.Context, in *AddJenisPembayaranReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadJenisPembayaran(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadJenisPembayaranResp, error)
	UpdateJenisPembayaran(ctx context.Context, in *UpdateJenisPembayaranReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadJenisPembayaranByMetode(ctx context.Context, in *ReadJenisPembayaranByMetodeReq, opts ...grpc1.CallOption) (*ReadJenisPembayaranByMetodeResp, error)
}

type jenisPembayaranServiceClient struct {
	cc *grpc1.ClientConn
}

func NewJenisPembayaranServiceClient(cc *grpc1.ClientConn) JenisPembayaranServiceClient {
	return &jenisPembayaranServiceClient{cc}
}

func (c *jenisPembayaranServiceClient) AddJenisPembayaran(ctx context.Context, in *AddJenisPembayaranReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.JenisPembayaranService/AddJenisPembayaran", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jenisPembayaranServiceClient) ReadJenisPembayaran(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadJenisPembayaranResp, error) {
	out := new(ReadJenisPembayaranResp)
	err := grpc1.Invoke(ctx, "/grpc.JenisPembayaranService/ReadJenisPembayaran", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jenisPembayaranServiceClient) UpdateJenisPembayaran(ctx context.Context, in *UpdateJenisPembayaranReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.JenisPembayaranService/UpdateJenisPembayaran", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jenisPembayaranServiceClient) ReadJenisPembayaranByMetode(ctx context.Context, in *ReadJenisPembayaranByMetodeReq, opts ...grpc1.CallOption) (*ReadJenisPembayaranByMetodeResp, error) {
	out := new(ReadJenisPembayaranByMetodeResp)
	err := grpc1.Invoke(ctx, "/grpc.JenisPembayaranService/ReadJenisPembayaranByMetode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JenisPembayaranService service

type JenisPembayaranServiceServer interface {
	AddJenisPembayaran(context.Context, *AddJenisPembayaranReq) (*google_protobuf.Empty, error)
	ReadJenisPembayaran(context.Context, *google_protobuf.Empty) (*ReadJenisPembayaranResp, error)
	UpdateJenisPembayaran(context.Context, *UpdateJenisPembayaranReq) (*google_protobuf.Empty, error)
	ReadJenisPembayaranByMetode(context.Context, *ReadJenisPembayaranByMetodeReq) (*ReadJenisPembayaranByMetodeResp, error)
}

func RegisterJenisPembayaranServiceServer(s *grpc1.Server, srv JenisPembayaranServiceServer) {
	s.RegisterService(&_JenisPembayaranService_serviceDesc, srv)
}

func _JenisPembayaranService_AddJenisPembayaran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJenisPembayaranReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JenisPembayaranServiceServer).AddJenisPembayaran(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JenisPembayaranService/AddJenisPembayaran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JenisPembayaranServiceServer).AddJenisPembayaran(ctx, req.(*AddJenisPembayaranReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JenisPembayaranService_ReadJenisPembayaran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JenisPembayaranServiceServer).ReadJenisPembayaran(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JenisPembayaranService/ReadJenisPembayaran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JenisPembayaranServiceServer).ReadJenisPembayaran(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JenisPembayaranService_UpdateJenisPembayaran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJenisPembayaranReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JenisPembayaranServiceServer).UpdateJenisPembayaran(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JenisPembayaranService/UpdateJenisPembayaran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JenisPembayaranServiceServer).UpdateJenisPembayaran(ctx, req.(*UpdateJenisPembayaranReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JenisPembayaranService_ReadJenisPembayaranByMetode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJenisPembayaranByMetodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JenisPembayaranServiceServer).ReadJenisPembayaranByMetode(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JenisPembayaranService/ReadJenisPembayaranByMetode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JenisPembayaranServiceServer).ReadJenisPembayaranByMetode(ctx, req.(*ReadJenisPembayaranByMetodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _JenisPembayaranService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.JenisPembayaranService",
	HandlerType: (*JenisPembayaranServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddJenisPembayaran",
			Handler:    _JenisPembayaranService_AddJenisPembayaran_Handler,
		},
		{
			MethodName: "ReadJenisPembayaran",
			Handler:    _JenisPembayaranService_ReadJenisPembayaran_Handler,
		},
		{
			MethodName: "UpdateJenisPembayaran",
			Handler:    _JenisPembayaranService_UpdateJenisPembayaran_Handler,
		},
		{
			MethodName: "ReadJenisPembayaranByMetode",
			Handler:    _JenisPembayaranService_ReadJenisPembayaranByMetode_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "jenisPembayaran.proto",
}

func init() { proto.RegisterFile("jenisPembayaran.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4a, 0xcd, 0xcb,
	0x2c, 0x0e, 0x48, 0xcd, 0x4d, 0x4a, 0xac, 0x4c, 0x2c, 0x4a, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x96, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94, 0x54, 0x42, 0x94, 0x28, 0x75, 0x32,
	0x72, 0x89, 0x3a, 0xa6, 0xa4, 0x78, 0xa1, 0xea, 0x0f, 0x4a, 0x2d, 0x14, 0xd2, 0xe1, 0x12, 0xcc,
	0x44, 0x17, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xc2, 0x94, 0x10, 0xd2, 0xe2, 0x12, 0xc8,
	0x4d, 0x2d, 0xc9, 0x4f, 0x49, 0x45, 0x52, 0xcc, 0x04, 0x56, 0x8c, 0x21, 0x2e, 0x24, 0xc6, 0xc5,
	0x56, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x2c, 0xc1, 0x0c, 0x56, 0x01, 0xe5, 0x29, 0xf9, 0x70, 0xc9,
	0x05, 0xa5, 0x26, 0xa2, 0x1b, 0xed, 0x54, 0xe9, 0x0b, 0x36, 0x00, 0xe4, 0x26, 0x6c, 0xb6, 0x30,
	0x62, 0xb7, 0x45, 0x69, 0x32, 0x23, 0x97, 0x3c, 0x5e, 0xe3, 0x8a, 0x0b, 0x06, 0xc0, 0x8f, 0x05,
	0x5c, 0xe2, 0x58, 0x1c, 0x05, 0x76, 0x4c, 0x28, 0x97, 0x50, 0x62, 0x4e, 0x0e, 0xa6, 0x6b, 0x98,
	0x35, 0xb8, 0x8d, 0x54, 0xf5, 0x40, 0x51, 0xa9, 0x47, 0xc0, 0x3f, 0x41, 0x58, 0x0c, 0x50, 0xea,
	0x61, 0xe4, 0x92, 0x08, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x1d, 0x0c, 0x91, 0x6c, 0xf4, 0x8d, 0x89,
	0x4b, 0x0c, 0xcd, 0xdc, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x6f, 0x2e, 0x21, 0xcc,
	0xa4, 0x28, 0x24, 0x0d, 0xf1, 0x3a, 0xd6, 0x44, 0x2a, 0x25, 0xa6, 0x07, 0x49, 0xdc, 0x7a, 0xb0,
	0xc4, 0xad, 0xe7, 0x0a, 0x4a, 0xdc, 0x4a, 0x0c, 0x42, 0x7e, 0x5c, 0xc2, 0x58, 0x42, 0x4b, 0x08,
	0x87, 0x06, 0x29, 0x59, 0x9c, 0x01, 0x0c, 0x0a, 0x58, 0x25, 0x06, 0xa1, 0x40, 0x2e, 0x51, 0xac,
	0xa1, 0x28, 0x24, 0x07, 0xd1, 0x89, 0x2b, 0x88, 0xf1, 0x38, 0x31, 0x87, 0x4b, 0x1a, 0x4f, 0x84,
	0x0a, 0xa9, 0x10, 0x11, 0xe7, 0x85, 0x52, 0xc4, 0xa5, 0x0c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xfd,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0xe7, 0x12, 0x2b, 0x2c, 0x04, 0x00, 0x00,
}
