// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jabatan.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	jabatan.proto

It has these top-level messages:
	AddJabatanReq
	ReadJabatanByNamaReq
	ReadJabatanByNamaResp
	ReadJabatanResp
	UpdateJabatanReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddJabatanReq struct {
	IdJabatan   string `protobuf:"bytes,1,opt,name=idJabatan" json:"idJabatan,omitempty"`
	NamaJabatan string `protobuf:"bytes,2,opt,name=namaJabatan" json:"namaJabatan,omitempty"`
	Status      string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *AddJabatanReq) Reset()                    { *m = AddJabatanReq{} }
func (m *AddJabatanReq) String() string            { return proto.CompactTextString(m) }
func (*AddJabatanReq) ProtoMessage()               {}
func (*AddJabatanReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddJabatanReq) GetIdJabatan() string {
	if m != nil {
		return m.IdJabatan
	}
	return ""
}

func (m *AddJabatanReq) GetNamaJabatan() string {
	if m != nil {
		return m.NamaJabatan
	}
	return ""
}

func (m *AddJabatanReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadJabatanByNamaReq struct {
	NamaJabatan string `protobuf:"bytes,1,opt,name=namaJabatan" json:"namaJabatan,omitempty"`
}

func (m *ReadJabatanByNamaReq) Reset()                    { *m = ReadJabatanByNamaReq{} }
func (m *ReadJabatanByNamaReq) String() string            { return proto.CompactTextString(m) }
func (*ReadJabatanByNamaReq) ProtoMessage()               {}
func (*ReadJabatanByNamaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadJabatanByNamaReq) GetNamaJabatan() string {
	if m != nil {
		return m.NamaJabatan
	}
	return ""
}

type ReadJabatanByNamaResp struct {
	IdJabatan   string `protobuf:"bytes,1,opt,name=idJabatan" json:"idJabatan,omitempty"`
	NamaJabatan string `protobuf:"bytes,2,opt,name=namaJabatan" json:"namaJabatan,omitempty"`
	Status      string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *ReadJabatanByNamaResp) Reset()                    { *m = ReadJabatanByNamaResp{} }
func (m *ReadJabatanByNamaResp) String() string            { return proto.CompactTextString(m) }
func (*ReadJabatanByNamaResp) ProtoMessage()               {}
func (*ReadJabatanByNamaResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadJabatanByNamaResp) GetIdJabatan() string {
	if m != nil {
		return m.IdJabatan
	}
	return ""
}

func (m *ReadJabatanByNamaResp) GetNamaJabatan() string {
	if m != nil {
		return m.NamaJabatan
	}
	return ""
}

func (m *ReadJabatanByNamaResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadJabatanResp struct {
	AllJabatan []*ReadJabatanByNamaResp `protobuf:"bytes,1,rep,name=allJabatan" json:"allJabatan,omitempty"`
}

func (m *ReadJabatanResp) Reset()                    { *m = ReadJabatanResp{} }
func (m *ReadJabatanResp) String() string            { return proto.CompactTextString(m) }
func (*ReadJabatanResp) ProtoMessage()               {}
func (*ReadJabatanResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadJabatanResp) GetAllJabatan() []*ReadJabatanByNamaResp {
	if m != nil {
		return m.AllJabatan
	}
	return nil
}

type UpdateJabatanReq struct {
	IdJabatan   string `protobuf:"bytes,1,opt,name=idJabatan" json:"idJabatan,omitempty"`
	NamaJabatan string `protobuf:"bytes,2,opt,name=namaJabatan" json:"namaJabatan,omitempty"`
	Status      string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateJabatanReq) Reset()                    { *m = UpdateJabatanReq{} }
func (m *UpdateJabatanReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateJabatanReq) ProtoMessage()               {}
func (*UpdateJabatanReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateJabatanReq) GetIdJabatan() string {
	if m != nil {
		return m.IdJabatan
	}
	return ""
}

func (m *UpdateJabatanReq) GetNamaJabatan() string {
	if m != nil {
		return m.NamaJabatan
	}
	return ""
}

func (m *UpdateJabatanReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddJabatanReq)(nil), "grpc.AddJabatanReq")
	proto.RegisterType((*ReadJabatanByNamaReq)(nil), "grpc.ReadJabatanByNamaReq")
	proto.RegisterType((*ReadJabatanByNamaResp)(nil), "grpc.ReadJabatanByNamaResp")
	proto.RegisterType((*ReadJabatanResp)(nil), "grpc.ReadJabatanResp")
	proto.RegisterType((*UpdateJabatanReq)(nil), "grpc.UpdateJabatanReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for JabatanService service

type JabatanServiceClient interface {
	AddJabatan(ctx context.Context, in *AddJabatanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadJabatan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadJabatanResp, error)
	UpdateJabatan(ctx context.Context, in *UpdateJabatanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadJabatanByNama(ctx context.Context, in *ReadJabatanByNamaReq, opts ...grpc1.CallOption) (*ReadJabatanByNamaResp, error)
}

type jabatanServiceClient struct {
	cc *grpc1.ClientConn
}

func NewJabatanServiceClient(cc *grpc1.ClientConn) JabatanServiceClient {
	return &jabatanServiceClient{cc}
}

func (c *jabatanServiceClient) AddJabatan(ctx context.Context, in *AddJabatanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.JabatanService/AddJabatan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jabatanServiceClient) ReadJabatan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadJabatanResp, error) {
	out := new(ReadJabatanResp)
	err := grpc1.Invoke(ctx, "/grpc.JabatanService/ReadJabatan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jabatanServiceClient) UpdateJabatan(ctx context.Context, in *UpdateJabatanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.JabatanService/UpdateJabatan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jabatanServiceClient) ReadJabatanByNama(ctx context.Context, in *ReadJabatanByNamaReq, opts ...grpc1.CallOption) (*ReadJabatanByNamaResp, error) {
	out := new(ReadJabatanByNamaResp)
	err := grpc1.Invoke(ctx, "/grpc.JabatanService/ReadJabatanByNama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JabatanService service

type JabatanServiceServer interface {
	AddJabatan(context.Context, *AddJabatanReq) (*google_protobuf.Empty, error)
	ReadJabatan(context.Context, *google_protobuf.Empty) (*ReadJabatanResp, error)
	UpdateJabatan(context.Context, *UpdateJabatanReq) (*google_protobuf.Empty, error)
	ReadJabatanByNama(context.Context, *ReadJabatanByNamaReq) (*ReadJabatanByNamaResp, error)
}

func RegisterJabatanServiceServer(s *grpc1.Server, srv JabatanServiceServer) {
	s.RegisterService(&_JabatanService_serviceDesc, srv)
}

func _JabatanService_AddJabatan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJabatanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JabatanServiceServer).AddJabatan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JabatanService/AddJabatan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JabatanServiceServer).AddJabatan(ctx, req.(*AddJabatanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JabatanService_ReadJabatan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JabatanServiceServer).ReadJabatan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JabatanService/ReadJabatan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JabatanServiceServer).ReadJabatan(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JabatanService_UpdateJabatan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJabatanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JabatanServiceServer).UpdateJabatan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JabatanService/UpdateJabatan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JabatanServiceServer).UpdateJabatan(ctx, req.(*UpdateJabatanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JabatanService_ReadJabatanByNama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJabatanByNamaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JabatanServiceServer).ReadJabatanByNama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JabatanService/ReadJabatanByNama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JabatanServiceServer).ReadJabatanByNama(ctx, req.(*ReadJabatanByNamaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _JabatanService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.JabatanService",
	HandlerType: (*JabatanServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddJabatan",
			Handler:    _JabatanService_AddJabatan_Handler,
		},
		{
			MethodName: "ReadJabatan",
			Handler:    _JabatanService_ReadJabatan_Handler,
		},
		{
			MethodName: "UpdateJabatan",
			Handler:    _JabatanService_UpdateJabatan_Handler,
		},
		{
			MethodName: "ReadJabatanByNama",
			Handler:    _JabatanService_ReadJabatanByNama_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "jabatan.proto",
}

func init() { proto.RegisterFile("jabatan.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0x6b, 0xc2, 0x40,
	0x10, 0x4d, 0xb4, 0x08, 0x4e, 0x48, 0x3f, 0xb6, 0x55, 0x24, 0xf6, 0x20, 0x7b, 0xf2, 0xb4, 0x82,
	0xbd, 0x14, 0x0a, 0x05, 0x0b, 0xbd, 0xf4, 0x90, 0x43, 0x4a, 0x7f, 0xc0, 0xc4, 0x6c, 0x83, 0x92,
	0xb8, 0x6b, 0xb2, 0x16, 0xfc, 0x37, 0xfd, 0xa9, 0xb2, 0x1b, 0x43, 0xa2, 0x51, 0x6f, 0x1e, 0x77,
	0xe6, 0xed, 0x7b, 0x6f, 0xde, 0x0c, 0xb8, 0x4b, 0x0c, 0x51, 0xe1, 0x8a, 0xc9, 0x4c, 0x28, 0x41,
	0x6e, 0xe2, 0x4c, 0xce, 0xbd, 0x61, 0x2c, 0x44, 0x9c, 0xf0, 0x89, 0xa9, 0x85, 0x9b, 0xdf, 0x09,
	0x4f, 0xa5, 0xda, 0x16, 0x10, 0x1a, 0x83, 0x3b, 0x8b, 0xa2, 0xaf, 0xe2, 0x5b, 0xc0, 0xd7, 0xe4,
	0x19, 0xba, 0x8b, 0xf2, 0x3d, 0xb0, 0x47, 0xf6, 0xb8, 0x1b, 0x54, 0x05, 0x32, 0x02, 0x67, 0x85,
	0x29, 0x96, 0xfd, 0x96, 0xe9, 0xd7, 0x4b, 0xa4, 0x0f, 0x9d, 0x5c, 0xa1, 0xda, 0xe4, 0x83, 0xb6,
	0x69, 0xee, 0x5f, 0xf4, 0x15, 0x9e, 0x02, 0x8e, 0x25, 0xd1, 0xc7, 0xd6, 0xc7, 0x14, 0xb5, 0xde,
	0x11, 0xa3, 0xdd, 0x60, 0xa4, 0x02, 0x7a, 0x27, 0x7e, 0xe6, 0xf2, 0x6a, 0x56, 0x7d, 0xb8, 0xab,
	0x09, 0x1a, 0xa9, 0x37, 0x00, 0x4c, 0x92, 0x4a, 0xab, 0x3d, 0x76, 0xa6, 0x43, 0xa6, 0xe3, 0x65,
	0x27, 0xbd, 0x05, 0x35, 0x38, 0x5d, 0xc2, 0xfd, 0x8f, 0x8c, 0x50, 0xf1, 0xeb, 0xc7, 0x3c, 0xfd,
	0x6f, 0xc1, 0xed, 0x1e, 0xf3, 0xcd, 0xb3, 0xbf, 0xc5, 0x9c, 0x6b, 0xef, 0xd5, 0x8a, 0xc9, 0x63,
	0xe1, 0xfa, 0x60, 0xe9, 0x5e, 0x9f, 0x15, 0x37, 0xc2, 0xca, 0x1b, 0x61, 0x9f, 0xfa, 0x46, 0xa8,
	0x45, 0xde, 0xc1, 0xa9, 0x0d, 0x48, 0xce, 0x00, 0xbd, 0x5e, 0x23, 0x0b, 0x9d, 0x02, 0xb5, 0xc8,
	0x0c, 0xdc, 0x83, 0xd9, 0x35, 0x83, 0x46, 0x1e, 0x07, 0x72, 0xc1, 0x82, 0x0f, 0x0f, 0x8d, 0x8c,
	0x89, 0x77, 0x36, 0xfc, 0xb5, 0x77, 0x69, 0x31, 0xd4, 0x0a, 0x3b, 0x46, 0xe1, 0x65, 0x17, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0x74, 0x17, 0xe8, 0x2d, 0x03, 0x00, 0x00,
}
